config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :sessions
    resources :teams
    resources :team_users
    resources :users do
      member do
        post :masquerade
        post :reverse_masquerade
      end
    end

    root to: "users#index"
  end
  # Authentication routes
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:update]
  namespace :identity do
    resource :account,            only: [:show, :update], controller: :account
    resource :email,              only: [:update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  # Solid Queue UI
  mount MissionControl::Jobs::Engine, at: "/admin/jobs"

  # App routes
  resources :lessons, only: :index

  root "pages#home"
end

app/models/user.rb
class User < ApplicationRecord
  include Avatarable
  include SanitizableNames

  attribute :terms_and_conditions

  has_secure_password

  belongs_to :team
  has_many :team_users, dependent: :destroy
  has_many :teams, through: :team_users

  has_many :email_verification_tokens, dependent: :destroy
  has_many :password_reset_tokens, dependent: :destroy
  has_many :sessions, dependent: :destroy

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [64, 64]
    attachable.variant :medium, resize_to_limit: [192, 192]
  end

  validates :first_name, :last_name, presence: true
  validates :email, disposable_email: true, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, allow_nil: true, length: { minimum: 8 }, format: { with: /(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])/ }
  validates :terms_and_conditions, acceptance: true, on: :create

  before_validation if: -> { email.present? } do
    self.email = email.downcase.strip
  end

  before_validation if: :email_changed?, unless: :new_record? do
    self.verified = false
  end

  after_update if: :password_digest_previously_changed? do
    sessions.where.not(id: Current.session).destroy_all
  end

  def name
    [first_name, last_name].compact.join(" ")
  end

  def obfuscated_name
    if last_name.present?
      "#{first_name} #{last_name.chars.first}."
    else
      first_name
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    skip_before_action :authenticate_admin, only: :reverse_masquerade

    def masquerade
      Current.session.masquerade_as!(requested_resource)
      redirect_to root_path
    end

    def reverse_masquerade
      Current.session.reverse_masquerade!
      redirect_to admin_users_path
    end

    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/views/admin/users/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", name: page.page_title) } %>

<header class="main-content__header">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <%= content_for(:header_middle) %>

  <div>
    <%= button_to "Login as #{page.resource.first_name}", masquerade_admin_user_path(page.resource), method: :post, class: "button" %>

    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if accessible_action?(page.resource, :edit) %>

    <%= button_to(
      t("administrate.actions.destroy"),
      [namespace, page.resource],
      class: "button button--danger",
      method: :delete,
      data: { turbo_confirm: t("administrate.actions.confirm") }
    ) if accessible_action?(page.resource, :destroy) %>
  </div>

  <%= content_for(:header_last) %>
</header>

<%= content_for(:before_main) %>

<% if content_for?(:main) %>
  <%= content_for(:main) %>
<% else %>
  <section class="main-content__body">
    <dl>
      <% page.attributes.each do |title, attributes| %>
        <fieldset class="<%= "field-unit--nested" if title.present? %>">
          <% if title.present? %>
            <legend><%= t "helpers.label.#{page.resource_name}.#{title}", default: title %></legend>
          <% end %>

          <% attributes.each do |attribute| %>
            <dt class="attribute-label" id="<%= attribute.name %>">
            <%= t(
              "helpers.label.#{resource_name}.#{attribute.name}",
              default: page.resource.class.human_attribute_name(attribute.name),
            ) %>
            </dt>

            <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
                ><%= render_field attribute, page: page %></dd>
          <% end %>
        </fieldset>
      <% end %>
    </dl>
  </section>
<% end %>

<%= content_for(:after_main) %>