config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :sessions
    resources :teams
    resources :team_users
    resources :users do
      member do
        post :masquerade
        post :reverse_masquerade
      end
    end

    root to: "users#index"
  end
  # Authentication routes
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:update]
  namespace :identity do
    resource :account,            only: [:show, :update], controller: :account
    resource :email,              only: [:update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  # Solid Queue UI
  mount MissionControl::Jobs::Engine, at: "/admin/jobs"

  # App routes
  resources :lessons, only: :index

  root "pages#home"
end

app/views/layouts/partials/_head.html.erb
<%= display_meta_tags(
  reverse: true,
  site: "Rapid Ruby Starter"
) %>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/partials/_user_dropdown.html.erb
<div class="relative ml-3" data-controller="toggle" data-toggle-click-outside="add">
  <div>
    <button data-action="toggle#toggle" type="button" class="flex max-w-xs items-center text-sm focus:outline-none focus:ring-2 focus:ring-offset-2" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
      <span class="sr-only">Open user menu</span>
      <span class="mr-3 text-gray-400 text-sm">Hi <%= Current.user.first_name %></span>
      <%= Current.user.letters_svg %>
    </button>
  </div>

  <div data-toggle-target="toggleable" data-css-class="hidden" class="hidden origin-top-right absolute top-full right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100 z-30" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
    <div class="px-4 py-3">
      <p class="text-sm">
        <%= t("nav.signed_in_as") %>
      </p>
      <p class="text-sm font-medium text-gray-900 truncate">
        <%= current_user.email %>
      </p>
    </div>
    <div class="py-1" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
      <%= link_to "Change email address", edit_identity_email_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem", tabindex: "-1" %>
      <%= link_to "Change password", edit_password_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem", tabindex: "-1" %>
      <%= link_to "Devices & Sessions", sessions_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem", tabindex: "-1" %>
    </div>
    <div class="py-1" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
      <%= button_to "Log out", session_path(Current.session), method: :delete, class: "block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem", tabindex: "-1" %>
    </div>
  </div>
</div>