config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :sessions
    resources :teams
    resources :team_users
    resources :users do
      member do
        post :masquerade
        post :reverse_masquerade
      end
    end

    root to: "users#index"
  end
  # Authentication routes
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:update]
  namespace :identity do
    resource :account,            only: [:show, :update], controller: :account
    resource :email,              only: [:update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  # Solid Queue UI
  mount MissionControl::Jobs::Engine, at: "/admin/jobs"

  # App routes
  resources :lessons, only: :index

  root "pages#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render partial: "layouts/partials/head" %>
  </head>

  <body class="text-gray-600">
    <%= render "shared/flash_alerts" %>

    <header class="bg-gray-800">
      <nav class="mx-auto max-w-7xl px-6 lg:px-8" aria-label="Top">
        <div class="flex w-full items-center justify-between border-b border-white/10 py-6 lg:border-none">
          <div class="flex items-center">
            <%= link_to root_path do %>
              <span class="sr-only">Rapid Ruby</span>
              <%= image_tag "rapid-ruby-stamp-dark.svg", alt: "Rapid Ruby", class: "h-10 w-auto" %>
            <% end %>
            <div class="ml-10 hidden space-x-8 lg:block">
              <%= link_to "Home", root_path, class: "text-base font-medium text-gray-200 hover:text-white" %>
              <%= link_to "Lessons", lessons_path, class: "text-base font-medium text-gray-200 hover:text-white" %>
            </div>
          </div>
          <div class="ml-10 space-x-4">
            <% if user_signed_in? %>
              <%= render UserDropdownComponent.new(current_user: Current.user, current_session: Current.session) %>
            <% else %>
              <%= link_to "Login", sign_in_path, class: "inline-block rounded-md text-sm sm:text-base font-medium text-gray-200 hover:text-white hover:underline" %>
              <%= link_to "Sign up", sign_up_path, class: "inline-block rounded-md border border-transparent bg-red-500 py-2 px-4 text-sm sm:text-base font-medium text-white hover:bg-opacity-75" %>
            <% end %>
          </div>
        </div>
        <div class="flex flex-wrap justify-center gap-x-6 py-4 lg:hidden">
          <%= link_to "Home", root_path, class: "text-base font-medium text-gray-200 hover:text-white" %>
          <%= link_to "Lessons", lessons_path, class: "text-base font-medium text-gray-200 hover:text-white" %>
        </div>
      </nav>
    </header>

    <main class="max-w-7xl mx-auto mt-10 lg:mt-16 px-6 lg:px-8">
      <%= render Admin::MasqueradeComponent.new(session: Current.session) %>

      <%= yield %>
    </main>
  </body>
</html>